const university_l = [
    "University of Moratuwa",
    "University of Colombo",
    "University of Sri Jayewardenepura",
    "University of Peradeniya",
    "University of Jaffna",
];
const major_l = [
    "Computer Science",
    "Business Administration",
    "Mechanical Engineering",
    "Psychology",
    "Nursing",
    "Biology",
    "Education",
    "Accounting",
    "Electrical Engineering",
    "Civil Engineering",
    "Political Science",
    "Economics",
    "Communications",
    "Marketing",
    "Finance",
    "Chemistry",
    "Sociology",
    "English Literature",
    "History",
    "Environmental Science",
    "Mathematics",
    "Physics",
    "Graphic Design",
    "Architecture",
    "Philosophy",
    "International Relations",
    "Criminal Justice",
    "Art",
    "Music",
    "Theater Arts",
    "Social Work",
    "Public Health",
    "Anthropology",
    "Information Technology",
    "Journalism",
    "Sports Management",
    "Biomedical Engineering",
    "Geology",
    "Hospitality Management",
    "Urban Planning",
];
const relationship_status_l = [
    "Married",
    "Divorced",
    "Single",
    "Widowed",
    "Dating",
    "Engaged",
    "Complicated",
];
const interested_in_l = ["Men", "Women", "Other"];
const gender_l = ["Male", "Female", "Other"];

export default {
    university_l,
    major_l,
    relationship_status_l,
    interested_in_l,
    gender_l,
};
